type RecordValue = Record<string, unknown>;
function number(v:unknown,name:string,min=-Infinity,max=Infinity):number {if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw new Error(`ورودی نامعتبر ${name}؛ محدوده ${min} تا ${max}`);return v;}
function list(v:unknown,name:string,max:number):RecordValue[]{if(!Array.isArray(v)||!v.length||v.length>max||v.some(x=>!x||typeof x!=='object'||Array.isArray(x)))throw new Error(`${name}: یک تا ${max} ردیف لازم است`);return v;}
function ident(v:unknown):string {if(typeof v!=='string'||!v.trim()||v.length>60)throw new Error('شناسه گره یا مسیر نامعتبر');return v.trim();}
type Node={id:string,fixed:number|null,elevation:number,demand:number,k:number,min:number|null,max:number|null};
type Edge={id:string,from:number,to:number,coefficient:number,exponent:number,offset:number,diameter:number};
function linear(a:number[][],b:number[]):number[]{const n=b.length,m=a.map((row,i)=>[...row,b[i]]);for(let k=0;k<n;k++){let p=k;for(let i=k+1;i<n;i++)if(Math.abs(m[i][k])>Math.abs(m[p][k]))p=i;if(Math.abs(m[p][k])<1e-16)throw new Error('شبکه تکین؛ اتصال به مرجع فشار و ضرایب مسیرها را بررسی کنید');[m[k],m[p]]=[m[p],m[k]];for(let i=k+1;i<n;i++){const f=m[i][k]/m[k][k];for(let j=k;j<=n;j++)m[i][j]-=f*m[k][j];}}const x=Array(n).fill(0);for(let i=n-1;i>=0;i--){x[i]=(m[i][n]-m[i].slice(i+1,n).reduce((s,v,j)=>s+v*x[i+1+j],0))/m[i][i];}return x;}
function flow(e:Edge,heads:number[]){const d=heads[e.from]-heads[e.to]+e.offset;return e.coefficient*Math.sign(d)*Math.abs(d)**e.exponent;}
export function network(input:RecordValue,air:boolean){
 const rawNodes=list(input.nodes,'nodes',60),rawEdges=list(input.edges,'edges',200);
 const nodes:Node[]=rawNodes.map(n=>({id:ident(n.id),fixed:n.fixed==null?null:number(n.fixed,'fixed'),elevation:air?0:number(n.elevation_m,'elevation_m'),demand:number(n.demand,air?'خروجی خالص m³/s (تزریق منفی)':'تقاضای ثابت L/min',air?-1000:0,1e6),k:air?0:number(n.k_metric??0,'K',0,10000),min:n.min==null?null:number(n.min,'حداقل'),max:n.max==null?null:number(n.max,'حداکثر')}));
 if(new Set(nodes.map(n=>n.id)).size!==nodes.length)throw new Error('شناسه گره تکراری است');
 if(nodes.some(n=>n.min!==null&&n.max!==null&&n.min>n.max))throw new Error('حداقل از حداکثر بیشتر است');
 const edges:Edge[]=rawEdges.map(e=>{const from=nodes.findIndex(n=>n.id===e.from),to=nodes.findIndex(n=>n.id===e.to);if(from<0||to<0||from===to)throw new Error('ابتدا/انتهای مسیر نامعتبر است');if(air)return {id:ident(e.id),from,to,coefficient:number(e.coefficient,'C [m³/s/Paⁿ]',1e-9,1000),exponent:number(e.exponent,'n',0.5,1),offset:number(e.offset_pa??0,'اختلاف فشار محرک Pa',-10000,10000),diameter:0};const length=number(e.length_m,'طول معادل m',0.001,1e6),d=number(e.diameter_mm,'قطر داخلی mm',1,5000)/1000,c=number(e.c_factor,'Hazen C',1,200),res=10.67*length/(60000**1.852*c**1.852*d**4.87);return {id:ident(e.id),from,to,coefficient:res**(-1/1.852),exponent:1/1.852,offset:0,diameter:d};});
 if(new Set(edges.map(e=>e.id)).size!==edges.length)throw new Error('شناسه مسیر تکراری است');
 const anchored=new Set(nodes.map((n,i)=>n.fixed!==null?i:-1).filter(i=>i>=0));if(!anchored.size)throw new Error('حداقل یک گره با فشار/هد ثابت لازم است');
 for(let pass=0;pass<nodes.length;pass++)for(const e of edges){if(anchored.has(e.from))anchored.add(e.to);if(anchored.has(e.to))anchored.add(e.from);}if(anchored.size!==nodes.length)throw new Error('گره جداافتاده یا بخش بدون مرجع فشار وجود دارد');
 const unknown=nodes.map((n,i)=>n.fixed===null?i:-1).filter(i=>i>=0);
 if(!unknown.length)throw new Error('حداقل یک گره با فشار مجهول لازم است');
 const initial=nodes.filter(n=>n.fixed!==null).reduce((s,n)=>s+n.fixed!,0)/nodes.filter(n=>n.fixed!==null).length;
 let heads=nodes.map(n=>n.fixed??(air?initial:Math.max(initial-1,n.elevation+1)));
 function balances(h:number[]){const b=nodes.map((n,i)=>n.demand+(air?0:n.k*Math.sqrt(Math.max(0,(h[i]-n.elevation)*0.0980665))));for(const e of edges){const q=flow(e,h);b[e.from]+=q;b[e.to]-=q;}return b;}
 const norm=(b:number[])=>Math.max(...unknown.map(i=>Math.abs(b[i])));
 const tolerance=air?1e-7:1e-4;let iterations=0;
 for(;iterations<150;iterations++){const b=balances(heads),err=norm(b);if(err<tolerance)break;const a=unknown.map(()=>unknown.map(()=>0));for(let j=0;j<unknown.length;j++){const idx=unknown[j],delta=Math.max(1e-6,Math.abs(heads[idx])*1e-6),trial=[...heads];trial[idx]+=delta;const bp=balances(trial);for(let i=0;i<unknown.length;i++)a[i][j]=(bp[unknown[i]]-b[unknown[i]])/delta;}const dx=linear(a,unknown.map(i=>-b[i]));let accepted=false;for(let scale=1;scale>=1/65536;scale/=2){const next=[...heads];unknown.forEach((idx,j)=>next[idx]+=scale*dx[j]);if(next.every(Number.isFinite)&&norm(balances(next))<err){heads=next;accepted=true;break;}}if(!accepted)throw new Error('حل شبکه همگرا نشد؛ داده‌ها و شرایط مرزی را بازبینی کنید');}
 const residual=norm(balances(heads));if(residual>=tolerance)throw new Error('حد تکرار حل شبکه؛ نتیجه قابل اتکا تولید نشد');
 const warnings:string[]=[];const nodeResults=nodes.map((n,i)=>{const pressure=air?heads[i]:(heads[i]-n.elevation)*0.0980665;const demand=n.demand+(air?0:n.k*Math.sqrt(Math.max(0,pressure)));if(!air&&pressure<0)warnings.push(`فشار منفی در گره ${n.id}؛ تأمین تقاضا از نظر فیزیکی معتبر نیست`);const checked=n.min!==null||n.max!==null,pass=(n.min===null||pressure>=n.min-1e-6)&&(n.max===null||pressure<=n.max+1e-6);if(!pass)warnings.push(`گره ${n.id}: فشار خارج از حدود ورودی پروژه`);return {id:n.id,[air?'pressure_pa':'pressure_bar']:pressure,...(!air?{total_head_m:heads[i]}:{}),[air?'net_demand_m3_s':'discharge_lpm']:demand,boundary:n.fixed!==null,criteria:checked?(pass?'pass':'fail'):'not_specified'};});
 if(nodes.some(n=>n.fixed===null&&n.min===null&&n.max===null))warnings.push('برای بعضی گره‌ها حد پذیرش تعریف نشده؛ همگرایی به معنی تأیید طراحی نیست');
 const edgeResults=edges.map(e=>({id:e.id,from:nodes[e.from].id,to:nodes[e.to].id,[air?'flow_m3_s':'flow_lpm']:flow(e,heads),[air?'driving_pressure_pa':'head_loss_m']:heads[e.from]-heads[e.to]+e.offset,...(!air?{velocity_mps:flow(e,heads)/60000/(Math.PI*e.diameter**2/4)}:{})}));
 warnings.push(air?'شبکه پایا با ضرایب ورودی و اختلاف فشار محرک علامت‌دار؛ جریان دوطرفه در بازشو بزرگ، گذرا و منحنی فن در این مدل نیست.':'شبکه پایا با منبع هد ثابت، Hazen–Williams و q=K√P؛ طول معادل اتصالات باید وارد شود. انتخاب ناحیه دوردست، منحنی پمپ و تأیید استاندارد خودکار نیست.');
 return {status:'warning',results:{iterations,max_mass_balance_error:residual,balance_unit:air?'m³/s':'L/min',nodes:nodeResults,edges:edgeResults,boundaries:nodes.flatMap((n,i)=>n.fixed!==null?[{id:n.id,net_supply:balances(heads)[i]}]:[])},warnings,trace:[air?'Qij = C sign(Pi-Pj+offset) |Pi-Pj+offset|^n':'hf = 10.67 L (Q/60000)^1.852 / [C^1.852 (D/1000)^4.87]; qspr = K sqrt(Pbar)','At unknown nodes: demand + sum(outgoing flow) = 0','Damped Newton; absolute nodal mass residual reported; non-convergence blocks result'],source_profile:air?'Steady power-law airflow network. NIST CONTAM 3.4 documentation (model reference; not CONTAM implementation/certification).':'Hazen–Williams and emitter nodal equations; EPA EPANET 2.2 manual (model reference; independent solver).'};
}
