begin;
create function pg_temp.check_ok(v boolean,msg text) returns void language plpgsql as $$ begin if not coalesce(v,false) then raise exception 'FAILED: %',msg; end if; end $$;
select set_config('request.jwt.claim.sub','cb5b4200-5b72-4ef9-b4d5-6dc714db2e26',true);
set local role authenticated;
select pg_temp.check_ok(not public.has_subscription(),'unpaid denied');
select pg_temp.check_ok((public.billing('status')->>'is_admin')::boolean=false,'regular user not admin');
do $$ begin
 begin perform public.billing('admin_list'); raise exception 'FAILED admin allowed'; exception when raise_exception then if SQLERRM like 'FAILED%' then raise; end if; end;
 begin perform public.billing('create_order','{"plan_code":"monthly"}'); raise exception 'FAILED sales allowed'; exception when raise_exception then if SQLERRM like 'FAILED%' then raise; end if; end;
 begin update public.subscriptions set valid_until=now()+interval '1 year'; raise exception 'FAILED direct write'; exception when insufficient_privilege then null; end;
end $$;
select pg_temp.check_ok(public.bootstrap_default_organization()<> '84dbb1b3-2b08-4721-be57-6c5a6ea31b70'::uuid,'private workspace');
select pg_temp.check_ok(public.bootstrap_default_organization()=public.bootstrap_default_organization(),'workspace idempotent');
select pg_temp.check_ok(not exists(select 1 from public.organizations where slug='rabin-azar-vira'),'tenant isolation');
reset role;
select set_config('request.jwt.claim.sub','5f4f63b9-fa28-4a95-bfb7-f4b671ae4a0b',true);
set local role authenticated;
select pg_temp.check_ok(public.has_subscription(),'owner access');
select public.billing('grant_trial','{"user_id":"cb5b4200-5b72-4ef9-b4d5-6dc714db2e26","note":"transactional test"}');
do $$ begin
 begin perform public.billing('grant_trial','{"user_id":"cb5b4200-5b72-4ef9-b4d5-6dc714db2e26","note":"repeat test"}'); raise exception 'FAILED repeat trial'; exception when raise_exception then if SQLERRM like 'FAILED%' then raise; end if; end;
end $$;
select public.billing('save_settings','{"sales_enabled":true,"bank_instructions":"TEST ONLY - rolled back"}');
reset role;
select set_config('request.jwt.claim.sub','cb5b4200-5b72-4ef9-b4d5-6dc714db2e26',true);
set local role authenticated;
select pg_temp.check_ok(public.has_subscription(),'trial active');
insert into public.engineering_projects(id,organization_id,name,created_by) values('11111111-1111-4111-8111-111111111111',public.bootstrap_default_organization(),'QA rolled back',auth.uid());
reset role;
insert into public.design_runs(id,project_id,module_key,engine_version,status,input_json,result_json,created_by) values('22222222-2222-4222-8222-222222222222','11111111-1111-4111-8111-111111111111','parking_smoke','0.5.1','calculated','{"flow_cfm":12000}','{"velocity_mps":11.327}',auth.uid());
set local role authenticated;
select pg_temp.check_ok((select result_json->>'velocity_mps'='11.327' from public.design_runs where id='22222222-2222-4222-8222-222222222222'),'saved result reopens');
update public.engineering_projects set name='QA edited' where id='11111111-1111-4111-8111-111111111111';
select pg_temp.check_ok((select name='QA edited' from public.engineering_projects where id='11111111-1111-4111-8111-111111111111'),'active project edit');

select public.billing('create_order','{"plan_code":"monthly","amount_toman":1,"months":12}');
select pg_temp.check_ok((select count(*)=1 and min(amount_toman)=690000 and min(months)=1 from public.subscription_orders where user_id=auth.uid()),'server price and duration');
select public.billing('create_order','{"plan_code":"monthly"}');
select pg_temp.check_ok((select count(*)=1 from public.subscription_orders where user_id=auth.uid()),'duplicate open order');
select public.billing('submit_payment',jsonb_build_object('order_id',(select id from public.subscription_orders where user_id=auth.uid()),'note','TEST payment 2026-09-29'));
reset role;
select set_config('request.jwt.claim.sub','5f4f63b9-fa28-4a95-bfb7-f4b671ae4a0b',true);
create temp table billing_test_before as select * from public.subscriptions where user_id='cb5b4200-5b72-4ef9-b4d5-6dc714db2e26';
create temp table billing_test_order as select id from public.subscription_orders where user_id='cb5b4200-5b72-4ef9-b4d5-6dc714db2e26';
grant select on billing_test_before,billing_test_order to authenticated;
set local role authenticated;
select pg_temp.check_ok(not exists(select 1 from public.engineering_projects where id='11111111-1111-4111-8111-111111111111'),'other tenant project invisible even to billing admin');
select pg_temp.check_ok(not exists(select 1 from public.design_runs where id='22222222-2222-4222-8222-222222222222'),'other tenant report invisible');
select public.billing('approve_order',jsonb_build_object('order_id',(select id from billing_test_order),'note','verified test','bank_reference','TEST-BANK-UNIQUE-001'));
select public.billing('approve_order',jsonb_build_object('order_id',(select id from billing_test_order),'note','repeat test','bank_reference','TEST-BANK-UNIQUE-001'));
reset role;
select pg_temp.check_ok((select s.valid_until=b.valid_until+interval '1 month' from public.subscriptions s join billing_test_before b using(user_id)),'renewal preserves trial and approves once');
select pg_temp.check_ok((select count(*)=1 from public.billing_events where action='approve_order' and subject_id='cb5b4200-5b72-4ef9-b4d5-6dc714db2e26'),'one approval audit');
select set_config('request.jwt.claim.sub','cb5b4200-5b72-4ef9-b4d5-6dc714db2e26',true);
set local role authenticated;
select public.billing('create_order','{"plan_code":"quarterly"}');
select public.billing('submit_payment',jsonb_build_object('order_id',(select id from public.subscription_orders where user_id=auth.uid() and status='pending'),'note','TEST repeated bank reference'));
reset role;
select set_config('request.jwt.claim.sub','5f4f63b9-fa28-4a95-bfb7-f4b671ae4a0b',true);
do $$ begin
 begin perform public.billing('approve_order',jsonb_build_object('order_id',(select id from public.subscription_orders where user_id='cb5b4200-5b72-4ef9-b4d5-6dc714db2e26' and status='submitted'),'note','duplicate reference test','bank_reference','TEST-BANK-UNIQUE-001')); raise exception 'FAILED duplicate bank receipt'; exception when unique_violation then null; end;
end $$;
select pg_temp.check_ok((select s.valid_until=b.valid_until+interval '1 month' from public.subscriptions s join billing_test_before b using(user_id)),'duplicate bank reference rolls back extension');
select public.billing('revoke_subscription','{"user_id":"cb5b4200-5b72-4ef9-b4d5-6dc714db2e26","note":"expiry test"}');
select set_config('request.jwt.claim.sub','cb5b4200-5b72-4ef9-b4d5-6dc714db2e26',true);
set local role authenticated;
select pg_temp.check_ok(not public.has_subscription(),'expired denied');
select pg_temp.check_ok(exists(select 1 from public.design_runs where id='22222222-2222-4222-8222-222222222222'),'expired report remains readable');
do $$ declare changed integer; begin
 update public.engineering_projects set name='EXPIRED WRITE' where id='11111111-1111-4111-8111-111111111111';get diagnostics changed=row_count;
 perform pg_temp.check_ok(changed=0,'expired update denied');
 begin insert into public.engineering_projects(organization_id,name) values(public.bootstrap_default_organization(),'EXPIRED INSERT'); raise exception 'FAILED expired insert'; exception when insufficient_privilege then null; end;
 begin insert into public.design_runs(project_id,module_key,engine_version) values('11111111-1111-4111-8111-111111111111','parking_smoke','0.5.1'); raise exception 'FAILED expired report insert'; exception when insufficient_privilege then null; end;
end $$;

select pg_temp.check_ok((select count(*)=2 from public.subscription_orders),'own order history retained');
reset role;
rollback;
select 'PASS: billing authorization, isolation, trial, pricing, renewal, idempotency, duplicate receipt rollback, expiry; all test data rolled back' as result;
