import { FormEvent, useEffect, useState } from 'react'
import { BatteryCharging, BellRing, Cable, RadioTower, ShieldAlert } from 'lucide-react'
import Field from '../components/Field'
import ResultPanel from '../components/ResultPanel'
import { calculate } from '../lib/api'
import { supabase } from '../lib/supabase'
import type { CalculationResponse, Project } from '../types'

export default function AlarmPage(){
 const [tab,setTab]=useState<'coverage'|'battery'|'drop'>('battery'),[result,setResult]=useState<CalculationResponse|null>(null),[busy,setBusy]=useState(false),[projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState('')
 const [coverage,setCoverage]=useState({area:'500',type:'smoke',height:'3'}),[battery,setBattery]=useState({standbyA:'0.35',standbyH:'24',alarmA:'1.8',alarmH:'0.5',margin:'25'}),[drop,setDrop]=useState({length:'120',current:'1.2',area:'1.5',rho:'0.0175',voltage:'24'})
 useEffect(()=>{supabase.from('engineering_projects').select('*').then(({data})=>data&&setProjects(data as Project[]))},[])
 const project=projects.find(p=>p.id===projectId)||null
 async function run(e:FormEvent){e.preventDefault();setBusy(true);setResult(null);try{if(tab==='coverage')setResult(await calculate('fire_alarm_preliminary',{floor_area_m2:+coverage.area,detector_type:coverage.type,ceiling_height_m:+coverage.height},project));if(tab==='battery')setResult(await calculate('fire_alarm_battery',{standby_current_a:+battery.standbyA,standby_hours:+battery.standbyH,alarm_current_a:+battery.alarmA,alarm_hours:+battery.alarmH,margin_percent:+battery.margin},project));if(tab==='drop')setResult(await calculate('voltage_drop',{one_way_length_m:+drop.length,current_a:+drop.current,cable_area_mm2:+drop.area,resistivity_ohm_mm2_m:+drop.rho,nominal_voltage_v:+drop.voltage},project))}catch(e){alert(e instanceof Error?e.message:'خطا')}finally{setBusy(false)}}
 return <div className="page-stack"><section className="module-hero alarm"><div><span className="eyebrow">FIRE ALARM / POWER</span><h1>اعلام حریق و مدارها</h1><p>محاسبات توان و مدار، کنترل افت ولتاژ و ابزارهای مقدماتی پوشش تجهیزات با هشدار صریح درباره معیارهای استاندارد.</p></div><div className="module-hero__symbol"><BellRing/><RadioTower/></div></section>
 <div className="project-context"><span>ذخیره در پروژه:</span><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">بدون ذخیره</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></div>
 <div className="calculator-layout"><section className="calc-card"><div className="segmented-tabs"><button type="button" className={tab==='coverage'?'active':''} onClick={()=>{setTab('coverage');setResult(null)}}><ShieldAlert size={17}/> پوشش مقدماتی</button><button type="button" className={tab==='battery'?'active':''} onClick={()=>{setTab('battery');setResult(null)}}><BatteryCharging size={17}/> باتری</button><button type="button" className={tab==='drop'?'active':''} onClick={()=>{setTab('drop');setResult(null)}}><Cable size={17}/> افت ولتاژ</button></div><form className="calc-form" onSubmit={run}>
 {tab==='coverage'&&<><div className="calc-banner danger">مقادیر پوشش این بخش فقط از راهنمای آموزشی قدیمی فایل آپلودی هستند و به‌هیچ‌وجه معیار نهایی طراحی جاری محسوب نمی‌شوند.</div><div className="form-grid two"><Field label="Floor Area" unit="m²" value={coverage.area} onChange={v=>setCoverage({...coverage,area:v})}/><Field label="Ceiling Height" unit="m" value={coverage.height} onChange={v=>setCoverage({...coverage,height:v})}/><label className="plain-field"><span>Detector Type</span><select value={coverage.type} onChange={e=>setCoverage({...coverage,type:e.target.value})}><option value="smoke">Smoke</option><option value="heat">Heat</option></select></label></div></>}
 {tab==='battery'&&<div className="form-grid two"><Field label="Standby Current" unit="A" value={battery.standbyA} onChange={v=>setBattery({...battery,standbyA:v})}/><Field label="Standby Time" unit="h" value={battery.standbyH} onChange={v=>setBattery({...battery,standbyH:v})}/><Field label="Alarm Current" unit="A" value={battery.alarmA} onChange={v=>setBattery({...battery,alarmA:v})}/><Field label="Alarm Time" unit="h" value={battery.alarmH} onChange={v=>setBattery({...battery,alarmH:v})}/><Field label="Design Margin" unit="%" value={battery.margin} onChange={v=>setBattery({...battery,margin:v})}/></div>}
 {tab==='drop'&&<div className="form-grid two"><Field label="One-way Length" unit="m" value={drop.length} onChange={v=>setDrop({...drop,length:v})}/><Field label="Circuit Current" unit="A" value={drop.current} onChange={v=>setDrop({...drop,current:v})}/><Field label="Cable Area" unit="mm²" value={drop.area} onChange={v=>setDrop({...drop,area:v})}/><Field label="Resistivity" unit="Ω·mm²/m" value={drop.rho} onChange={v=>setDrop({...drop,rho:v})}/><Field label="Nominal Voltage" unit="V" value={drop.voltage} onChange={v=>setDrop({...drop,voltage:v})}/></div>}
 <button className="primary-button calc-submit" disabled={busy}>{busy?'در حال محاسبه…':'اجرای محاسبه'}</button></form></section><ResultPanel data={result}/></div>
 </div>
}
