import { FormEvent, useEffect, useState } from 'react'
import { Building2, ChevronLeft, CirclePlus, MapPin, Search, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Project } from '../types'
import { formatDate, formatNumber } from '../lib/persian'
import StatusPill from '../components/StatusPill'

const empty = { name:'', project_code:'', client_name:'', building_use:'مسکونی', city:'قزوین', address_text:'', floors_above:'', floors_below:'', total_area_m2:'', erp_project_id:'' }

export default function ProjectsPage(){
 const [projects,setProjects]=useState<Project[]>([]),[search,setSearch]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[org,setOrg]=useState<string|null>(null)
 async function load(){const m=await supabase.from('organization_members').select('organization_id').limit(1).maybeSingle();setOrg(m.data?.organization_id||null);const p=await supabase.from('engineering_projects').select('*').order('updated_at',{ascending:false});if(p.data)setProjects(p.data as Project[])}
 useEffect(()=>{load()},[])
 async function submit(e:FormEvent){e.preventDefault();if(!org)return alert('ابتدا عضویت سازمان را از داشبورد فعال کنید.');setBusy(true);const u=(await supabase.auth.getUser()).data.user;const {error}=await supabase.from('engineering_projects').insert({organization_id:org,name:form.name,project_code:form.project_code||null,client_name:form.client_name||null,building_use:form.building_use,city:form.city||null,address_text:form.address_text||null,floors_above:Number(form.floors_above)||0,floors_below:Number(form.floors_below)||0,total_area_m2:Number(form.total_area_m2)||null,erp_project_id:form.erp_project_id||null,created_by:u?.id,status:'active'});setBusy(false);if(error)alert(error.message);else{setOpen(false);setForm(empty);load()}}
 const filtered=projects.filter(p=>`${p.name} ${p.project_code||''} ${p.client_name||''}`.toLowerCase().includes(search.toLowerCase()))
 return <div className="page-stack"><div className="page-title-row"><div><span className="eyebrow">PROJECT CONTROL</span><h1>پروژه‌های مهندسی</h1><p>هر پروژه یک ظرف مستقل برای ورودی‌ها، محاسبات، گزارش‌ها و سوابق بازبینی است.</p></div><button className="primary-button" onClick={()=>setOpen(true)}><CirclePlus size={18}/> پروژه جدید</button></div>
 <div className="toolbar"><div className="search-box"><Search size={17}/><input placeholder="جستجو در پروژه‌ها…" value={search} onChange={e=>setSearch(e.target.value)}/></div><span>{formatNumber(filtered.length,0)} پروژه</span></div>
 <div className="project-grid">{filtered.map(p=><article className="project-card" key={p.id}><div className="project-card__top"><div className="project-card__icon"><Building2/></div><StatusPill tone={p.status==='approved'?'ok':p.status==='review'?'warn':'info'}>{p.status}</StatusPill></div><h3>{p.name}</h3><div className="project-code">{p.project_code||'بدون کد پروژه'}</div><div className="project-card__meta"><span><MapPin size={14}/>{p.city||'—'}</span><span>کاربری: {p.building_use||'—'}</span><span>مساحت: {p.total_area_m2?formatNumber(p.total_area_m2,0)+' m²':'—'}</span><span>آخرین تغییر: {formatDate(p.updated_at)}</span></div><div className="project-card__foot"><span>{p.client_name||'کارفرما ثبت نشده'}</span><ChevronLeft size={18}/></div></article>)}</div>
 {open&&<div className="modal-backdrop"><form className="modal-card" onSubmit={submit}><div className="modal-head"><div><span className="eyebrow">NEW ENGINEERING PROJECT</span><h2>تعریف پروژه جدید</h2></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X/></button></div><div className="form-grid two">{[['نام پروژه','name'],['کد پروژه','project_code'],['کارفرما','client_name'],['شناسه پروژه ERP','erp_project_id'],['شهر','city'],['آدرس','address_text'],['طبقات روی زمین','floors_above'],['طبقات زیرزمین','floors_below'],['مساحت کل m²','total_area_m2']].map(([l,k])=><label className="plain-field" key={k}><span>{l}</span><input type={k.includes('floors')||k.includes('area')?'number':'text'} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} required={k==='name'}/></label>)}<label className="plain-field"><span>کاربری</span><select value={form.building_use} onChange={e=>setForm({...form,building_use:e.target.value})}><option>مسکونی</option><option>اداری</option><option>تجاری</option><option>مختلط</option><option>پارکینگ</option><option>صنعتی</option><option>درمانی</option></select></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>انصراف</button><button className="primary-button" disabled={busy}>{busy?'در حال ثبت…':'ثبت پروژه'}</button></div></form></div>}
 </div>
}
