import { useEffect, useState } from 'react'
import { FileJson, FileText, Printer } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { formatDate } from '../lib/persian'
import type { DesignRun, Project } from '../types'
import StatusPill from '../components/StatusPill'

export default function ReportsPage(){
 const [runs,setRuns]=useState<DesignRun[]>([]),[projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState<DesignRun|null>(null)
 useEffect(()=>{Promise.all([supabase.from('design_runs').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('engineering_projects').select('*')]).then(([r,p])=>{if(r.data){setRuns(r.data as DesignRun[]);setSelected((r.data as DesignRun[])[0]||null)};if(p.data)setProjects(p.data as Project[])})},[])
 const project=selected?projects.find(p=>p.id===selected.project_id):null
 function download(){if(!selected)return;const blob=new Blob([JSON.stringify({project,run:selected},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rabin-engineering-${selected.id}.json`;a.click();URL.revokeObjectURL(a.href)}
 return <div className="page-stack"><div className="page-title-row"><div><span className="eyebrow">ENGINEERING REPORTS</span><h1>گزارش‌ها و سوابق محاسبات</h1><p>هر گزارش بر اساس Run ثبت‌شده، نسخه موتور، هشدارها و Calculation Hash قابل بازسازی است.</p></div><div className="report-actions"><button className="secondary-button" onClick={download} disabled={!selected}><FileJson size={17}/> JSON</button><button className="primary-button" onClick={()=>window.print()} disabled={!selected}><Printer size={17}/> چاپ / PDF</button></div></div>
 <div className="reports-layout"><aside className="reports-list">{runs.map(r=><button key={r.id} className={selected?.id===r.id?'active':''} onClick={()=>setSelected(r)}><div><strong>{r.module_key}</strong><span>{formatDate(r.created_at)}</span></div>{r.warnings?.length?<StatusPill tone="warn">{r.warnings.length}</StatusPill>:<StatusPill tone="ok">OK</StatusPill>}</button>)}</aside><section className="report-preview">{!selected?<div className="empty-result"><FileText/><strong>گزارشی وجود ندارد</strong></div>:<div className="report-sheet"><header><div><strong>RABIN AZAR VIRA</strong><span>Fire Engineering Calculation Report</span></div><div className="report-stamp">ENGINEERING<br/>RECORD</div></header><div className="report-title"><span>{project?.project_code||'PROJECT'}</span><h2>{project?.name||'پروژه'}</h2><p>{selected.module_key}</p></div><div className="report-meta-grid"><div><span>Engine Version</span><strong>{selected.engine_version}</strong></div><div><span>Run Status</span><strong>{selected.status}</strong></div><div><span>Date</span><strong>{formatDate(selected.created_at)}</strong></div><div><span>Hash</span><strong className="hash-short">{selected.calculation_hash?.slice(0,16)||'—'}</strong></div></div><h3>ورودی‌ها</h3><pre>{JSON.stringify(selected.input_json,null,2)}</pre><h3>خروجی‌ها</h3><pre>{JSON.stringify(selected.result_json,null,2)}</pre><h3>هشدارهای مهندسی</h3>{selected.warnings?.length?<ul className="report-warning-list">{selected.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul>:<p>هشدار داخلی ثبت نشده است.</p>}<h3>ردیابی محاسبه</h3><ol className="report-trace">{selected.calculation_trace?.map((t,i)=><li key={i}><code>{t}</code></li>)}</ol><footer>این گزارش ابزار کمک‌مهندسی است و جایگزین بازبینی استاندارد جاری، ضوابط AHJ و تأیید متخصص مسئول نیست.</footer></div>}</section></div>
 </div>
}
