import { useState, type FormEvent } from 'react'
import type { CalculationResponse, Project } from '../types'
import { calculate } from '../lib/api'
import ResultPanel from './ResultPanel'
type Row=Record<string,string>
const waterNodes:Row[]=[{id:'S',fixed:'50',elevation_m:'0',demand:'0',k_metric:'0',min:'',max:''},{id:'A',fixed:'',elevation_m:'10',demand:'0',k_metric:'80',min:'1',max:''},{id:'B',fixed:'',elevation_m:'10',demand:'0',k_metric:'80',min:'1',max:''}]
const waterEdges:Row[]=[{id:'P1',from:'S',to:'A',length_m:'30',diameter_mm:'65',c_factor:'120'},{id:'P2',from:'A',to:'B',length_m:'5',diameter_mm:'32',c_factor:'120'}]
const airNodes:Row[]=[{id:'OUT',fixed:'0',demand:'0',min:'',max:''},{id:'F1',fixed:'',demand:'-0.6',min:'25',max:'60'},{id:'F2',fixed:'',demand:'-0.6',min:'25',max:'60'}]
const airEdges:Row[]=[{id:'L1',from:'F1',to:'OUT',coefficient:'0.085',exponent:'0.5',offset_pa:'0'},{id:'L2',from:'F2',to:'OUT',coefficient:'0.085',exponent:'0.5',offset_pa:'0'},{id:'SHAFT',from:'F1',to:'F2',coefficient:'0.2',exponent:'0.5',offset_pa:'0'}]
export default function NetworkCalculator({air=false,project}:{air?:boolean,project:Project|null}){
 const [nodes,setNodes]=useState<Row[]>(air?airNodes:waterNodes),[edges,setEdges]=useState<Row[]>(air?airEdges:waterEdges),[basis,setBasis]=useState(''),[result,setResult]=useState<CalculationResponse|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const nodeColumns=air?[['id','شناسه'],['fixed','فشار ثابت Pa؛ خالی=مجهول'],['demand','خروجی m³/s؛ تزریق منفی'],['min','حداقل Pa'],['max','حداکثر Pa']]:[['id','شناسه'],['fixed','هد کل ثابت m؛ خالی=مجهول'],['elevation_m','تراز m'],['demand','مصرف ثابت L/min'],['k_metric','K متریک اسپرینکلر'],['min','حداقل bar'],['max','حداکثر bar']]
 const edgeColumns=air?[['id','شناسه'],['from','از گره'],['to','به گره'],['coefficient','C: m³/s/Paⁿ'],['exponent','توان n'],['offset_pa','فشار محرک Pa']]:[['id','شناسه'],['from','از گره'],['to','به گره'],['length_m','طول معادل m'],['diameter_mm','قطر داخلی mm'],['c_factor','Hazen C']]
 function convert(rows:Row[]){return rows.map(row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[k,['id','from','to'].includes(k)?v:(v.trim()===''?null:Number(v))])))}
 async function run(e:FormEvent){e.preventDefault();setBusy(true);setError('');setResult(null);try{setResult(await calculate(air?'airflow_network':'hydraulic_network',{nodes:convert(nodes),edges:convert(edges),design_basis:basis},project))}catch(e){setError(e instanceof Error?e.message:'خطای حل شبکه')}finally{setBusy(false)}}
 function table(rows:Row[],setRows:(r:Row[])=>void,cols:string[][],kind:string){return <div className="network-table"><table><thead><tr>{cols.map(([k,l])=><th key={k}>{l}</th>)}<th>حذف</th></tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{cols.map(([k,l])=><td key={k}>{k==='from'||k==='to'?<select aria-label={`${kind} ${i+1} ${l}`} value={row[k]} onChange={e=>{setRows(rows.map((r,j)=>j===i?{...r,[k]:e.target.value}:r));setResult(null)}}><option value="">انتخاب</option>{nodes.map((n,j)=><option key={j} value={n.id}>{n.id}</option>)}</select>:<input aria-label={`${kind} ${i+1} ${l}`} type={k==='id'?'text':'number'} step="any" required={!['fixed','min','max'].includes(k)} value={row[k]??''} onChange={e=>{setRows(rows.map((r,j)=>j===i?{...r,[k]:e.target.value}:r));setResult(null)}}/>}</td>)}<td><button type="button" className="secondary-button" disabled={rows.length<2} onClick={()=>{setRows(rows.filter((_,j)=>j!==i));setResult(null)}} aria-label={`حذف ${kind} ${i+1}`}>×</button></td></tr>)}</tbody></table></div>}
 return <section className="calc-card network-card"><h2>{air?'شبکه فشار مثبت طبقات':'شبکه هیدرولیک اسپرینکلر و رایزر'}</h2><p>{air?'فشار ثابت را فقط برای مرجع‌ها وارد کنید. برای هر طبقه یک گره و برای هر درز، در یا اتصال شفت یک مسیر تعریف کنید.':'گره منبع: هد کل = تراز منبع + هد فشار. برای اسپرینکلر K متریک و برای هیدرانت تقاضای ثابت را وارد کنید. حلقه و انشعاب پشتیبانی می‌شود.'}</p><div className="calc-banner warning">اعداد نمونه صرفاً برای آزمون مدل هستند. حدود پذیرش، سناریوی باز/بسته بودن درها یا اسپرینکلرهای فعال و مبنای طراحی را برای پروژه خود تعیین کنید.</div><form onSubmit={run}><fieldset disabled={busy}><label className="plain-field"><span>مبنای طراحی، ویرایش مرجع و سناریوی محاسبه</span><input required value={basis} onChange={e=>{setBasis(e.target.value);setResult(null)}} placeholder="مرجع / ویرایش / سناریو / دلیل حدود پذیرش"/></label><h3>گره‌ها</h3>{table(nodes,setNodes,nodeColumns,'گره')}<button type="button" className="secondary-button" onClick={()=>{setNodes([...nodes,{...(air?airNodes[1]:waterNodes[1]),id:`N${nodes.length+1}`}]);setResult(null)}} disabled={nodes.length>=60}>افزودن گره</button><h3>مسیرها</h3>{table(edges,setEdges,edgeColumns,'مسیر')}<button type="button" className="secondary-button" onClick={()=>{setEdges([...edges,{...(air?airEdges[0]:waterEdges[0]),id:`E${edges.length+1}`,from:nodes[0].id,to:nodes.at(-1)!.id}]);setResult(null)}} disabled={edges.length>=200}>افزودن مسیر</button>{air&&<details><summary>محاسبه ضرایب و اثر باد / دودکشی</summary><p>برای روزنه: C = Cd × A × √(2/ρ) و n=0.5. فشار محرک در جهت «از» به «به» مثبت است؛ سهم دودکشی در تراز مسیر برابر g×(ρبه−ρاز)×z و فشار باد مرز برابر Cp×ρ×U²/2 است. فشار ثابت، مبنای ارتفاع و فشار محرک باید سازگار باشند؛ یک اثر را دوبار وارد نکنید. در باز را در سناریوی مستقل با ضریب مناسب مدل کنید.</p></details>}<button className="primary-button calc-submit" disabled={busy}>{busy?'در حال حل شبکه…':'حل شبکه و کنترل حدود ورودی'}</button></fieldset></form>{error&&<div role="alert" className="warning-item">{error}</div>}<ResultPanel data={result}/></section>
}
